#Script for common package installation on MatrixDS docker image
PKGS <- c(
     "DT",
     "FinCal",
     "RCurl",
     "RJDBC",
     "broom",
     "caret",
     "devtools",
     "expm",
     "feather",
     "flexdashboard",
     "forcats",
     "foreign",
     "ggplot2",
     "googleVis",
     "htmlwidgets",
     "knitr",
     "leaflet",
     "lubridate",
     "magrittr",
     "mailR",
     "mlbench",
     "openxlsx",
     "packrat",
     "plotROC",
     "plotly",
     "plumber",
     "readr",
     "readxl",
     "rgdal",
     "rmarkdown",
     "roxygen2",
     "rvest",
     "shiny",
     "shinydashboard",
     "sparklyr",
     "stringr",
     "testthat",
     "tidyverse"
)

install.packages(PKGS, dependencies = TRUE)
